export type InterviewState =
  | 'SETUP'
  | 'READY'
  | 'QUESTION'
  | 'LISTENING'
  | 'EVALUATING'
  | 'FOLLOW_UP'
  | 'NEXT_QUESTION'
  | 'COMPLETE'
  | 'PAUSED'
  | 'RECONNECTING'
  | 'SILENCE_WARNING'
  | 'TERMINATED'
  | 'INVALID_CHEATING'
  | 'SESSION_EXPIRED'
  | 'MEDIA_PAUSED';

export const INTERVIEW_CONFIG = {
  MAX_RESPONSE_TIME_SECONDS: 240, // 4 minutes
  SILENCE_WARNING_THRESHOLD_SECONDS: 10,
  PING_INTERVAL_MS: 5000,
} as const;
